/**
 * Types for AI-powered operations in the Recall system.
 *
 * These types define the contract between the AI facade (server-side)
 * and the UI components that consume AI-generated content.
 */

import type { BloomsLevel, FsrsRating } from './recall.js'

// ============================================================================
// AI Generation Output Types
// ============================================================================

/** A concept generated by AI for a given topic */
export interface GeneratedConcept {
  title: string
  summary: string
  whyItMatters: string
  bloomsLevel: BloomsLevel
}

/** A question generated by AI for a concept */
export interface GeneratedQuestion {
  questionText: string
  /** Bloom's level the question targets (may differ from the concept's level) */
  questionType: BloomsLevel
}

/** AI evaluation of a user's answer */
export interface AnswerEvaluation {
  /** Detailed feedback explaining what was correct/incorrect */
  feedback: string
  /** AI-suggested FSRS rating based on answer quality */
  suggestedRating: FsrsRating
}
