export {
  createNode,
  createOutlineNode,
  deleteNode,
  evaluateQuery,
  evaluateEditorQuery,
  getAllNodes,
  getBacklinks,
  getChildNodes,
  getGroupedBacklinks,
  getNode,
  getNodesBySupertag,
  getOwnerChain,
  getSupertags,
  searchNodes,
  setNodeProperties,
  swapOrder,
  updateNodeContent,
} from './server/operations.js'

export type {
  BacklinksResult,
  BacklinkGroup,
  BacklinkNodeSummary,
  BacklinkOriginKind,
  ChildNodesResult,
  CreateNodeInput,
  CreateOutlineNodeInput,
  CreateOutlineNodeResult,
  CreateNodeResult,
  EditorQueryResultNode,
  EvaluateEditorQueryResult,
  EvaluateQueryInput,
  EvaluateQueryResult,
  GroupedBacklinksResult,
  GetAllNodesInput,
  GetNodeInput,
  GetNodesBySupertagInput,
  GetOwnerChainInput,
  GetOwnerChainResult,
  SearchNodesInput,
  SearchNodesResult,
  SetNodePropertiesInput,
  SetNodePropertiesResult,
  SwapOrderInput,
  SwapOrderResult,
  OutlineAppliedField,
  OutlineAppliedSupertag,
  SupertagsResult,
  UpdateNodeContentInput,
  UpdateNodeContentResult,
} from './server/operations.js'
