/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarOauthCallbackRouteImport } from './routes/calendar.oauth-callback'
import { Route as AppsAppIdRouteImport } from './routes/apps.$appId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarOauthCallbackRoute = CalendarOauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => CalendarRoute,
} as any)
const AppsAppIdRoute = AppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRouteWithChildren
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/calendar/oauth-callback': typeof CalendarOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRouteWithChildren
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/calendar/oauth-callback': typeof CalendarOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRouteWithChildren
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/calendar/oauth-callback': typeof CalendarOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/inbox'
    | '/settings'
    | '/apps/$appId'
    | '/calendar/oauth-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/inbox'
    | '/settings'
    | '/apps/$appId'
    | '/calendar/oauth-callback'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/inbox'
    | '/settings'
    | '/apps/$appId'
    | '/calendar/oauth-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRouteWithChildren
  InboxRoute: typeof InboxRoute
  SettingsRoute: typeof SettingsRoute
  AppsAppIdRoute: typeof AppsAppIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/oauth-callback': {
      id: '/calendar/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/calendar/oauth-callback'
      preLoaderRoute: typeof CalendarOauthCallbackRouteImport
      parentRoute: typeof CalendarRoute
    }
    '/apps/$appId': {
      id: '/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CalendarRouteChildren {
  CalendarOauthCallbackRoute: typeof CalendarOauthCallbackRoute
}

const CalendarRouteChildren: CalendarRouteChildren = {
  CalendarOauthCallbackRoute: CalendarOauthCallbackRoute,
}

const CalendarRouteWithChildren = CalendarRoute._addFileChildren(
  CalendarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRouteWithChildren,
  InboxRoute: InboxRoute,
  SettingsRoute: SettingsRoute,
  AppsAppIdRoute: AppsAppIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
